# Generated by Django 6.0.4 on 2026-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funciones',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='funciones',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funciones',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='funciones',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
